### ISSUE TITLE
Bug locks out operator until cache is cleared

### ISSUE THREAD

**Issue by CryptoMaximalist** [FoxxMD/context-mod#122]
As mentioned here https://discord.com/channels/921051902576304170/921054230985470032/1032858232575766568

Not urgent or prohibitive, just documenting

```
15:37:38 CDT debug  : [Delayed Activities] No Activities ready to queue
15:37:38 CDT error  : [App] unhandledRejection: Regex(es) did not match the value given.

Regex: /^\s*(?<entityType>\/[ru]\/|[ru]\/|u_)*(?<name>[\w-]+)*\s*$/

Value: a:t5_tv7pf

Sample regex: https://regexr.com/6bq1g
InvalidRegexError: Regex(es) did not match the value given.

Regex: /^\s*(?<entityType>\/[ru]\/|[ru]\/|u_)*(?<name>[\w-]+)*\s*$/

Value: a:t5_tv7pf

Sample regex: https://regexr.com/6bq1g
    at parseRedditEntity (/app/src/util.js:699:15)
    at /app/src/Web/Client/ClientBotInstance.js:23:77
    at [Array.map](http://array.map/) (<anonymous>)
    at ClientBotInstance.getAccessibleSubreddits (/app/src/Web/Client/ClientBotInstance.js:23:39)
    at ClientBotInstance.canUserAccessBot (/app/src/Web/Client/ClientBotInstance.js:34:21)
    at /app/src/Web/Client/index.js:729:43
    at Array.some (<anonymous>)
    at /app/src/Web/Client/index.js:729:31
    at Array.find (<anonymous>)
    at defaultInstance (/app/src/Web/Client/index.js:725:52)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at defaultSession (/app/src/Web/Client/index.js:688:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at ensureAuthenticated (/app/src/Web/Client/index.js:253:13)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at redirectBotsNotAuthed (/app/src/Web/Client/index.js:753:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at initHeartbeat (/app/src/Web/Client/index.js:499:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
InvalidRegexError: Regex(es) did not match the value given.

Regex: /^\s*(?<entityType>\/[ru]\/|[ru]\/|u_)*(?<name>[\w-]+)*\s*$/

Value: a:t5_tv7pf

Sample regex: https://regexr.com/6bq1g
    at parseRedditEntity (/app/src/util.js:699:15)
    at /app/src/Web/Client/ClientBotInstance.js:23:77
    at [Array.map](http://array.map/) (<anonymous>)
    at ClientBotInstance.getAccessibleSubreddits (/app/src/Web/Client/ClientBotInstance.js:23:39)
    at ClientBotInstance.canUserAccessBot (/app/src/Web/Client/ClientBotInstance.js:34:21)
    at /app/src/Web/Client/index.js:729:43
    at Array.some (<anonymous>)
    at /app/src/Web/Client/index.js:729:31
    at Array.find (<anonymous>)
    at defaultInstance (/app/src/Web/Client/index.js:725:52)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at defaultSession (/app/src/Web/Client/index.js:688:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at ensureAuthenticated (/app/src/Web/Client/index.js:253:13)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at redirectBotsNotAuthed (/app/src/Web/Client/index.js:753:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at initHeartbeat (/app/src/Web/Client/index.js:499:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
15:37:36 CDT error  : [App] unhandledRejection: Regex(es) did not match the value given.

Regex: /^\s*(?<entityType>\/[ru]\/|[ru]\/|u_)*(?<name>[\w-]+)*\s*$/

Value: a:t5_tv7pf

Sample regex: https://regexr.com/6bq1g
InvalidRegexError: Regex(es) did not match the value given.

Regex: /^\s*(?<entityType>\/[ru]\/|[ru]\/|u_)*(?<name>[\w-]+)*\s*$/

Value: a:t5_tv7pf

Sample regex: https://regexr.com/6bq1g
    at parseRedditEntity (/app/src/util.js:699:15)
    at /app/src/Web/Client/ClientBotInstance.js:23:77
    at [Array.map](http://array.map/) (<anonymous>)
    at ClientBotInstance.getAccessibleSubreddits (/app/src/Web/Client/ClientBotInstance.js:23:39)
    at ClientBotInstance.canUserAccessBot (/app/src/Web/Client/ClientBotInstance.js:34:21)
    at /app/src/Web/Common/User/ClientUser.js:13:71
    at Array.filter (<anonymous>)
    at ClientUser.canAccessInstance (/app/src/Web/Common/User/ClientUser.js:13:57)
    at instanceWithPermissions (/app/src/Web/Client/index.js:458:62)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at defaultSession (/app/src/Web/Client/index.js:688:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at initHeartbeat (/app/src/Web/Client/index.js:499:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at ensureAuthenticatedApi (/app/src/Web/Client/index.js:261:13)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
InvalidRegexError: Regex(es) did not match the value given.

Regex: /^\s*(?<entityType>\/[ru]\/|[ru]\/|u_)*(?<name>[\w-]+)*\s*$/

Value: a:t5_tv7pf

Sample regex: https://regexr.com/6bq1g
    at parseRedditEntity (/app/src/util.js:699:15)
    at /app/src/Web/Client/ClientBotInstance.js:23:77
    at [Array.map](http://array.map/) (<anonymous>)
    at ClientBotInstance.getAccessibleSubreddits (/app/src/Web/Client/ClientBotInstance.js:23:39)
    at ClientBotInstance.canUserAccessBot (/app/src/Web/Client/ClientBotInstance.js:34:21)
    at /app/src/Web/Common/User/ClientUser.js:13:71
    at Array.filter (<anonymous>)
    at ClientUser.canAccessInstance (/app/src/Web/Common/User/ClientUser.js:13:57)
    at instanceWithPermissions (/app/src/Web/Client/index.js:458:62)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at defaultSession (/app/src/Web/Client/index.js:688:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at initHeartbeat (/app/src/Web/Client/index.js:499:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at ensureAuthenticatedApi (/app/src/Web/Client/index.js:261:13)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
15:37:36 CDT error  : [App] unhandledRejection: Regex(es) did not match the value given.

Regex: /^\s*(?<entityType>\/[ru]\/|[ru]\/|u_)*(?<name>[\w-]+)*\s*$/

Value: a:t5_tv7pf

Sample regex: https://regexr.com/6bq1g
InvalidRegexError: Regex(es) did not match the value given.

Regex: /^\s*(?<entityType>\/[ru]\/|[ru]\/|u_)*(?<name>[\w-]+)*\s*$/

Value: a:t5_tv7pf

Sample regex: https://regexr.com/6bq1g
    at parseRedditEntity (/app/src/util.js:699:15)
    at /app/src/Web/Client/ClientBotInstance.js:23:77
    at [Array.map](http://array.map/) (<anonymous>)
    at ClientBotInstance.getAccessibleSubreddits (/app/src/Web/Client/ClientBotInstance.js:23:39)
    at ClientBotInstance.canUserAccessBot (/app/src/Web/Client/ClientBotInstance.js:34:21)
    at /app/src/Web/Common/User/ClientUser.js:13:71
    at Array.filter (<anonymous>)
    at ClientUser.canAccessInstance (/app/src/Web/Common/User/ClientUser.js:13:57)
    at instanceWithPermissions (/app/src/Web/Client/index.js:458:62)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at defaultSession (/app/src/Web/Client/index.js:688:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at initHeartbeat (/app/src/Web/Client/index.js:499:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at ensureAuthenticatedApi (/app/src/Web/Client/index.js:261:13)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
InvalidRegexError: Regex(es) did not match the value given.

Regex: /^\s*(?<entityType>\/[ru]\/|[ru]\/|u_)*(?<name>[\w-]+)*\s*$/

Value: a:t5_tv7pf

Sample regex: https://regexr.com/6bq1g
    at parseRedditEntity (/app/src/util.js:699:15)
    at /app/src/Web/Client/ClientBotInstance.js:23:77
    at [Array.map](http://array.map/) (<anonymous>)
    at ClientBotInstance.getAccessibleSubreddits (/app/src/Web/Client/ClientBotInstance.js:23:39)
    at ClientBotInstance.canUserAccessBot (/app/src/Web/Client/ClientBotInstance.js:34:21)
    at /app/src/Web/Common/User/ClientUser.js:13:71
    at Array.filter (<anonymous>)
    at ClientUser.canAccessInstance (/app/src/Web/Common/User/ClientUser.js:13:57)
    at instanceWithPermissions (/app/src/Web/Client/index.js:458:62)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at defaultSession (/app/src/Web/Client/index.js:688:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at initHeartbeat (/app/src/Web/Client/index.js:499:9)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at ensureAuthenticatedApi (/app/src/Web/Client/index.js:261:13)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
15:37:34 CDT debug  : [App] Checking onboarding invites...
15:37:33 CDT debug  : [Delayed Activities] No Activities ready to queue
15:37:30 CDT info   :  Activity processing queue started RUNNING with 0 queued activities
15:37:30 CDT info   :  Event polling STARTED
15:37:30 CDT debug  : [Polling] [Submission] Polling Interval Started
15:37:30 CDT debug  :  Starting own streams => SUBMISSION 30s interval
15:37:30 CDT debug  :  Polling NEWSUB => create new dedicated stream
15:37:29 CDT info   : [App] CryptoContextModBot from localhost:8095 => CONNECTED
15:37:25 CDT debug  :  Retrieving mod permissions for bot
15:37:24 CDT info   :  Checks updated
15:37:24 CDT info   :  Found Checks -- Submission: 4 | Comment: 0
15:37:24 CDT info   :  Found 3 Runs with 4 Checks
```

**Comment by FoxxMD** [comment]
This was fixed in 2d8b7f7b86ee1326a39bd0cda2993854cf553e8a and is available in `latest`/master
