### ISSUE TITLE
If app crashes multiple times it can cause a 403

### ISSUE THREAD

**Issue by OmgImAlexis** [FoxxMD/context-mod#51]
After starting up my server the app loaded but redis did not. This caused multiple crashes over an hour or so.

After starting redis and then the app I'm now greeted with the following.

```
0|index  | 2021-11-29T22:49:36+10:30 info   : [Web] Web UI started: http://localhost:8085
0|index  | 2021-11-29T22:49:36+10:30 info   : [App] API started => localhost:8095
0|index  | 2021-11-29T22:49:36+10:30 info   : [App] Beginning bot init on startup...
0|index  | 2021-11-29T22:49:36+10:30 info   : [App] Operators: None Specified
0|index  | 2021-11-29T22:49:36+10:30 error  : [App] An error occurred while trying to initialize the Reddit API Client which would prevent the entire application from running.
0|index  | 2021-11-29T22:49:36+10:30 error  : [App] Error Message: 403 - "Blocked"
0|index  | 2021-11-29T22:49:36+10:30 error  : [App] Bot undefined cannot recover from this error and must be re-built
0|index  | 2021-11-29T22:49:36+10:30 error  : [App] 403 - "Blocked"
0|index  | StatusCodeError: 403 - "Blocked"
0|index  |     at new StatusCodeError (CWD/node_modules/request-promise-core/lib/errors.js:32:15)
0|index  |     at Request.plumbing.callback (CWD/node_modules/request-promise-core/lib/plumbing.js:104:33)
0|index  |     at Request.RP$callback [as _callback] (CWD/node_modules/request-promise-core/lib/plumbing.js:46:31)
0|index  |     at Request.self.callback (CWD/node_modules/request/request.js:185:22)
0|index  |     at Request.emit (node:events:390:28)
0|index  |     at Request.<anonymous> (CWD/node_modules/request/request.js:1154:10)
0|index  |     at Request.emit (node:events:390:28)
0|index  |     at IncomingMessage.<anonymous> (CWD/node_modules/request/request.js:1076:12)
0|index  |     at Object.onceWrapper (node:events:509:28)
0|index  |     at IncomingMessage.emit (node:events:402:35)
0|index  |     at endReadableNT (node:internal/streams/readable:1340:12)
0|index  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

**Comment by OmgImAlexis** [comment]
Actually this may be caused by the fact reddit's modmail is down. I'll keep an eye on this. If it's still an issue once mod mail is working again I'll let you know.

**Comment by FoxxMD** [comment]
im also experiencing 403 when trying to start up the bot in a separate instance, but my main one is still going and i can still login so account isn't suspended. I think you are correct this is probably related to the issues they had this morning. Someone else had this same issue and reported it in [r/redditdev](https://www.reddit.com/r/redditdev/comments/r4uw8f/will_i_ever_be_unblocked_from_the_reddit_api/)

**Comment by OmgImAlexis** [comment]
Mod mail is up and I still cannot connect. This is an issue as this means the sub is without any mod bot.
Exact same error too.
